on:
  push:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions: write-all
    if: |
      contains(join(github.event.commits.*.modified, ','), 'X/') ||
      contains(join(github.event.commits.*.added, ','), 'X/') ||
      contains(join(github.event.commits.*.removed, ','), 'X/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build dev container
        uses: devcontainers/ci@v0.3
        with:
          push: always
          imageName: ghcr.io/dopsi/gh-actions-rust-test
          cacheFrom: ghcr.io/dopsi/gh-actions-rust-test

  build:
    runs-on: ubuntu-latest
    needs: docker
    if: always()
    container:
      image: ghcr.io/dopsi/gh-actions-c-test
      options: --user vscode

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          cargo build

  test:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ghcr.io/dopsi/gh-actions-c-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          cargo test
  
  mutants:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ghcr.io/dopsi/gh-actions-c-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          cargo mutants -e main.rs
